import test from 'node:test'
import assert from 'node:assert/strict'
import { mkdtemp, mkdir, readFile, writeFile, rm, symlink, readdir } from 'node:fs/promises'
import os from 'node:os'
import path from 'node:path'
import { hostsDiff } from '../dist-electron/hosts-diff.js'
import { VhostraStore } from '../dist-electron/store.js'
import { exportFullBackup, previewFullBackup, restoreFullDatabase, proveDatabaseEquality } from '../dist-electron/backup.js'
const fixture = async task => { const root=await mkdtemp(path.join(os.tmpdir(),'vhostra-reconcile-unit-'));const store=new VhostraStore(root);const project=path.join(root,'project');await mkdir(project);await writeFile(path.join(project,'sentinel'),'untouched');try{await task({root,store,project})}finally{await rm(root,{recursive:true,force:true})} }
test('canonical comparison detects behavior changes, requires choices, replaces without changing identity, and skips reimport',()=>fixture(async({root,store,project})=>{
 const state=await store.addSite({name:'Example',url:'http://example.test',documentRoot:project,aliases:['www.example.test']});const local=state.sites.find(site=>!site.builtIn);const bundle=path.join(root,'bundle.json');await store.exportBundle(bundle)
 const data=JSON.parse(await readFile(bundle,'utf8'));const host=data.configuration.virtualHosts.find(host=>!host.builtIn);host.indexFiles=['home.php'];host.rewriteEnabled=false;host.logs.access=false;await writeFile(bundle,JSON.stringify(data));let preview=await store.previewBundle(bundle);assert.equal(preview.sites[0].disposition,'conflict');assert.deepEqual(preview.sites[0].differences.sort(),['indexFiles','logs','rewriteEnabled'])
 await assert.rejects(store.importBundle(bundle),/review required/);assert.equal((await store.getState()).virtualHosts.find(host=>host.id===local.vhostId).rewriteEnabled,true)
 const result=await store.importBundle(bundle,{},preview.checksum,{}, {'example.test':'replace'});assert.equal(result.summary.replaced,1);assert.equal((await store.getState()).sites.find(site=>!site.builtIn).id,local.id);assert.equal(await readFile(path.join(project,'sentinel'),'utf8'),'untouched')
 preview=await store.previewBundle(bundle);assert.equal(preview.sites[0].disposition,'equivalent');assert.equal((await store.importBundle(bundle)).summary.skipped,1);assert.equal((await store.getState()).sites.length,2)
}))
test('ambiguous hostname collisions are incompatible and cannot replace two local Sites',()=>fixture(async({root,store,project})=>{
 await store.addSite({name:'A',url:'http://a.test',documentRoot:project});await store.addSite({name:'B',url:'http://b.test',documentRoot:project});const bundle=path.join(root,'bundle.json');await store.exportBundle(bundle);const data=JSON.parse(await readFile(bundle,'utf8'));data.configuration.sites=data.configuration.sites.filter(site=>site.builtIn||site.name==='A');data.configuration.virtualHosts=data.configuration.virtualHosts.filter(host=>host.builtIn||host.hostname==='a.test');data.configuration.virtualHosts.find(host=>!host.builtIn).aliases=['b.test'];await writeFile(bundle,JSON.stringify(data));assert.equal((await store.previewBundle(bundle)).sites[0].disposition,'incompatible');await assert.rejects(store.importBundle(bundle,{},undefined,{}, {'a.test':'replace'}),/incompatible/);assert.equal((await store.importBundle(bundle,{},undefined,{}, {'a.test':'skip'})).summary.skipped,1);assert.equal((await store.getState()).sites.length,3)
}))
function fakeRuntime() {
 let databases=new Map([['example_db','original data']]);let accounts=[{user:'reader',host:'localhost',role:false,create:"CREATE USER 'reader'@'localhost' IDENTIFIED BY PASSWORD 'private-hash'",grants:["GRANT SELECT ON example_db.* TO 'reader'@'localhost'"]}];let caches={redis:'bind 127.0.0.1\n',memcached:'-l 127.0.0.1\n'};let failed=false
 return {databaseBackupStatus:async()=> 'running',backupDatabaseMetadata:async()=>({version:'11.8.3',plugins:['mysql_native_password']}),listDatabases:async()=>[...databases.keys()].sort(),backupAccounts:async()=>structuredClone(accounts),backupCacheState:async()=>structuredClone(caches),restoreBackupCacheState:async value=>{caches={...caches,...value}},exportDatabase:async(name,file)=>writeFile(file,databases.get(name)),prepareBackupDatabase:async(name)=>databases.set(name,''),importDatabase:async(name,file)=>{databases.set(name,await readFile(file,'utf8'));if(failed){failed=false;throw Error('Injected actual write failure')}},deleteDatabase:async name=>databases.delete(name),restoreBackupAccounts:async next=>{accounts=accounts.filter(account=>!next.some(item=>item.user===account.user&&item.host===account.host)).concat(structuredClone(next))},removeBackupAccounts:async next=>{accounts=accounts.filter(account=>!next.some(item=>item.user===account.user&&item.host===account.host))},reapplyBackupGrants:async()=>{},setData:value=>databases.set('example_db',value),setGrants:value=>accounts[0].grants=[value],inject:()=>{failed=true},data:()=>databases.get('example_db')}
}
test('full backup private payload/checksums, uncertain database conflict, account grant conflict, skip, replace and data rollback',()=>fixture(async({root,store})=>{
 await store.getState();const runtime=fakeRuntime();const file=path.join(root,'full.json');await exportFullBackup(store,runtime,file,()=>{});const manifest=JSON.parse(await readFile(file,'utf8'));assert.doesNotMatch(JSON.stringify(manifest),/private-hash|IDENTIFIED/)
 let plan=await previewFullBackup(file,runtime,()=>{});assert.equal(plan.items.find(item=>item.category==='database').disposition,'conflict');assert.equal(plan.items.find(item=>item.category==='account').disposition,'equivalent');await assert.rejects(restoreFullDatabase(plan,runtime,{},store.layout.backups,()=>{}),/review required/)
 await proveDatabaseEquality(plan,runtime,'database:example_db',path.join(root,'compare'));let result=await restoreFullDatabase(plan,runtime,{},store.layout.backups,()=>{});assert.equal(result.summary.skipped,4)
 runtime.setData('changed data');runtime.setGrants("GRANT INSERT ON example_db.* TO 'reader'@'localhost'");plan=await previewFullBackup(file,runtime,()=>{});assert.equal(plan.items.find(item=>item.category==='account').disposition,'conflict');assert.doesNotMatch(JSON.stringify(plan.items),/private-hash/)
 const choices=Object.fromEntries(plan.items.filter(item=>item.disposition==='conflict').map(item=>[item.key,'replace']));runtime.inject();await assert.rejects(restoreFullDatabase(plan,runtime,choices,store.layout.backups,()=>{}),/Original data\/accounts recovered/);assert.equal(runtime.data(),'changed data')
 plan=await previewFullBackup(file,runtime,()=>{});result=await restoreFullDatabase(plan,runtime,choices,store.layout.backups,()=>{});assert.equal(result.summary.replaced,2);assert.equal(runtime.data(),'original data')
}))
test('proven equality is invalidated by subsequent writes; changed inputs and unsafe backup paths refuse restoration',()=>fixture(async({root,store})=>{
 await store.getState();const runtime=fakeRuntime();const file=path.join(root,'full.json');await exportFullBackup(store,runtime,file,()=>{});let plan=await previewFullBackup(file,runtime,()=>{});await proveDatabaseEquality(plan,runtime,'database:example_db',path.join(root,'compare'));runtime.setData('external modification');await assert.rejects(restoreFullDatabase(plan,runtime,{},store.layout.backups,()=>{}),/changed after comparison/);assert.equal(runtime.data(),'external modification')
 const manifest=JSON.parse(await readFile(file,'utf8'));manifest.databases[0].file='../outside.sql';await writeFile(file,JSON.stringify(manifest));await assert.rejects(previewFullBackup(file,runtime,()=>{}),/Invalid backup member path/)
 manifest.databases[0].file=manifest.privateAccounts.file;await writeFile(file,JSON.stringify(manifest));await assert.rejects(previewFullBackup(file,runtime,()=>{}),/duplicate backup member/)
}))

test('identical restoration makes no SQL writes and retains only ten completed owned recoveries',()=>fixture(async({root,store})=>{
 await store.getState();const runtime=fakeRuntime();const file=path.join(root,'full.json');await exportFullBackup(store,runtime,file,()=>{});const plan=await previewFullBackup(file,runtime,()=>{});await proveDatabaseEquality(plan,runtime,'database:example_db',path.join(root,'compare'));
 runtime.prepareBackupDatabase=async()=>{throw Error('No database writes expected')};runtime.reapplyBackupGrants=async()=>{throw Error('No grant writes expected')};runtime.restoreBackupAccounts=async selected=>assert.equal(selected.length,0);
 const retained=path.join(store.layout.backups,'database-restore-00000000-0000-0000-0000-000000000000');await mkdir(retained,{recursive:true});await writeFile(path.join(retained,'journal.json'),JSON.stringify({owner:'vhostra',kind:'full-backup-restore',state:'requires-recovery',createdAt:'2000-01-01'}));
 for(let i=0;i<12;i++)await restoreFullDatabase(plan,runtime,{},store.layout.backups,()=>{});
 const entries=(await readdir(store.layout.backups)).filter(name=>name.startsWith('database-restore-'));assert.equal(entries.length,11);assert.equal(JSON.parse(await readFile(path.join(retained,'journal.json'),'utf8')).state,'requires-recovery');
 const journal=JSON.parse(await readFile(path.join(store.layout.backups,entries.find(name=>name!==path.basename(retained)),'journal.json'),'utf8'));assert.ok(journal.items.every(item=>item.outcome==='skipped'));assert.equal(journal.imported,0);
}))

test('Hosts review separates independent changes, retains line endings and bounds large diffs',()=>{
 const source='# old comment\r\n127.0.0.1 localhost\r\n# stable anchor\r\n192.0.2.1 example.test\r\n';const draft=source.replace('# old comment','# new comment').replace('192.0.2.1','192.0.2.2');const review=hostsDiff(source,draft);assert.equal(review.removedLines,2);assert.equal(review.addedLines,2);assert.equal(review.diff.match(/@@ -/g).length,2);assert.doesNotMatch(review.diff,/[-+]# stable anchor/);
 const large=hostsDiff('#'.repeat(200000),'!'.repeat(200000));assert.equal(large.truncated,true);assert.ok(Buffer.byteLength(large.diff)<=128*1024);
})
