import { contextBridge, ipcRenderer, type IpcRendererEvent } from 'electron'

const api = Object.freeze({
  getOnboarding: () => ipcRenderer.invoke('vhostra:get-onboarding'),
  saveOnboarding: (preferences: unknown) => ipcRenderer.invoke('vhostra:save-onboarding', preferences),
  setupOnboarding: () => ipcRenderer.invoke('vhostra:setup-onboarding'),
  previewNativeImport: (server?: string, directory = false) => ipcRenderer.invoke('vhostra:preview-native-import', server, directory),
  applyNativeImport: () => ipcRenderer.invoke('vhostra:apply-native-import'),
  getResources: (refreshStorage = false) => ipcRenderer.invoke('vhostra:get-resources', refreshStorage),
  getState: () => ipcRenderer.invoke('vhostra:get-state'),
  saveSettings: (settings: unknown) => ipcRenderer.invoke('vhostra:save-settings', settings),
  addSite: (input: unknown) => ipcRenderer.invoke('vhostra:add-site', input),
  updateSite: (input: unknown) => ipcRenderer.invoke('vhostra:update-site', input),
  removeSite: (id: string) => ipcRenderer.invoke('vhostra:remove-site', id),
  setVirtualHostRewrite: (id: string, enabled: boolean) => ipcRenderer.invoke('vhostra:set-vhost-rewrite', id, enabled),
  chooseDocumentRoot: () => ipcRenderer.invoke('vhostra:choose-document-root'),
  chooseConfigurationLocation: () => ipcRenderer.invoke('vhostra:choose-configuration-location'),
  migrateConfigurationLocation: (directory: string) => ipcRenderer.invoke('vhostra:migrate-configuration-location', directory),
  openSite: (url: string) => ipcRenderer.invoke('vhostra:open-site', url),
  getStorageLayout: () => ipcRenderer.invoke('vhostra:get-storage-layout'),
  listPersistentLogs: () => ipcRenderer.invoke('vhostra:list-persistent-logs'),
  readLogTail: (relative: string) => ipcRenderer.invoke('vhostra:read-log-tail', relative),
  exportConfiguration: (request: unknown) => ipcRenderer.invoke('vhostra:export-configuration', request),
  previewConfigurationImport: () => ipcRenderer.invoke('vhostra:preview-configuration-import'),
  importConfiguration: () => ipcRenderer.invoke('vhostra:import-configuration'),
  getRuntimeStatus: () => ipcRenderer.invoke('vhostra:get-runtime-status'),
  startServices: () => ipcRenderer.invoke('vhostra:start-services'),
  stopServices: () => ipcRenderer.invoke('vhostra:stop-services'),
  restartServices: () => ipcRenderer.invoke('vhostra:restart-services'),
  quitApplication: (mode: 'keep-services' | 'stop-services' | 'minimize-to-tray') => ipcRenderer.invoke('vhostra:quit-application', mode),
  checkPort: (port: number) => ipcRenderer.invoke('vhostra:check-port', port),
  findAvailablePort: (port: number) => ipcRenderer.invoke('vhostra:find-available-port', port),
  reloadWebServer: () => ipcRenderer.invoke('vhostra:reload-web-server'),
  setOptionalService: (id: 'redis' | 'memcached', enabled: boolean) => ipcRenderer.invoke('vhostra:set-optional-service', id, enabled),
  listManagedServices: () => ipcRenderer.invoke('vhostra:list-managed-services'),
  controlManagedService: (id: 'web' | 'mariadb' | 'redis' | 'memcached', action: 'start' | 'stop' | 'restart') => ipcRenderer.invoke('vhostra:control-managed-service', id, action),
  listDatabases: () => ipcRenderer.invoke('vhostra:list-databases'),
  listPhpExtensions: () => ipcRenderer.invoke('vhostra:list-php-extensions'),
  managePhpExtension: (id: string, action: 'install' | 'enable' | 'disable' | 'remove') => ipcRenderer.invoke('vhostra:manage-php-extension', id, action),
  getCwebpStatus: () => ipcRenderer.invoke('vhostra:get-cwebp-status'),
  configureCwebp: (enabled: boolean) => ipcRenderer.invoke('vhostra:configure-cwebp', enabled),
  createDatabase: (input: unknown) => ipcRenderer.invoke('vhostra:create-database', input),
  openPhpMyAdmin: (database?: string) => ipcRenderer.invoke('vhostra:open-phpmyadmin', database),
  importDatabase: (database: string) => ipcRenderer.invoke('vhostra:import-database', database),
  exportDatabase: (database: string) => ipcRenderer.invoke('vhostra:export-database', database),
  repairDatabase: (database: string) => ipcRenderer.invoke('vhostra:repair-database', database),
  deleteDatabase: (database: string) => ipcRenderer.invoke('vhostra:delete-database', database),
  syncAllHosts: () => ipcRenderer.invoke('vhostra:sync-all-hosts'),
  syncHosts: (id: string) => ipcRenderer.invoke('vhostra:sync-hosts', id),
  hostsStatus: (id: string) => ipcRenderer.invoke('vhostra:hosts-status', id),
  getAppInfo: () => ipcRenderer.invoke('vhostra:get-app-info'),
  checkForUpdates: () => ipcRenderer.invoke('vhostra:check-for-updates'),
  onRuntimeStatus: (listener: (status: unknown) => void) => { const handler = (_event: IpcRendererEvent, status: unknown) => listener(status); ipcRenderer.on('vhostra:runtime-status', handler); return () => ipcRenderer.removeListener('vhostra:runtime-status', handler) },
})

contextBridge.exposeInMainWorld('vhostra', api)

if (process.env.NODE_ENV === 'development') console.info('[Vhostra preload] Secure bridge exposed as window.vhostra')
