import { ErrorNotice } from './ErrorNotice'
import { useState } from 'react'
import type { BackupPreview } from '../types/desktop-api'
export type BackupChoices = Record<string, 'keep' | 'replace' | 'skip'>
export function BackupConflicts({ backup, choices, onChange, disabled, onCompared, onComparing }: { backup: BackupPreview; choices: BackupChoices; onChange: (choices: BackupChoices) => void; disabled: boolean; onCompared?: (backup: BackupPreview) => void; onComparing?: (busy: boolean) => void }) {
  const [comparing, setComparing] = useState(false); const [error, setError] = useState<string | null>(null)
  const stateItems = [...(backup.configurationItems ?? []), ...(backup.databaseItems ?? [])]
  const conflicts = backup.sites.filter(site => ['conflict', 'incompatible'].includes(site.disposition))
  return <>{error && <ErrorNotice error={error}/>} {stateItems.map(item => <section key={item.key} className="mt-4 rounded-lg border border-[#E5E5E5] p-4">
    <h3 className="text-sm font-medium">{item.category} · <span className="selectable">{item.name}</span> · {item.disposition === 'equivalent' ? 'Identical — skip' : item.disposition}</h3><p className="mt-2 text-xs leading-5 text-[#606060]">{item.detail}</p>{item.local && item.incoming ? <details className="mt-3 text-xs"><summary>Compare existing and backup</summary><pre className="selectable-diagnostic mt-2 max-h-48 overflow-auto whitespace-pre-wrap">{JSON.stringify({ existing: item.local, backup: item.incoming }, null, 2)}</pre></details> : null}
    {['conflict', 'incompatible'].includes(item.disposition) && <label className="mt-3 block text-sm">Action<select disabled={disabled || comparing} className="input mt-2" value={choices[item.key] ?? ''} onChange={event => onChange({ ...choices, [item.key]: event.target.value as BackupChoices[string] })}><option value="" disabled>Choose an action</option><option value="keep">Keep Existing</option>{item.disposition !== 'incompatible' && <option value="replace">Replace with Backup</option>}<option value="skip">Skip</option></select></label>}
    {item.category === 'database' && item.disposition === 'conflict' && onCompared && <button disabled={disabled || comparing} className="mt-3 h-9 rounded-full border border-[#E5E5E5] px-4 text-sm font-medium" onClick={() => { setComparing(true); onComparing?.(true); setError(null); void window.vhostra!.compareBackupDatabase(item.key).then(result => onCompared({ ...backup, databaseItems: backup.databaseItems!.map(current => current.key === result.key ? result : current) })).catch(reason => setError(String(reason))).finally(() => { setComparing(false); onComparing?.(false) }) }}>Compare database data</button>}
    {item.disposition === 'conflict' && choices[item.key] && stateItems.some(current => current.category === item.category && current.disposition === 'conflict' && !choices[current.key]) && <button disabled={disabled || comparing} className="mt-3 h-9 rounded-full border border-[#E5E5E5] px-4 text-sm font-medium" onClick={() => onChange({ ...Object.fromEntries(stateItems.filter(current => current.category === item.category && current.disposition === 'conflict' && !choices[current.key]).map(current => [current.key, choices[item.key]])), ...choices })}>Apply choice to remaining {item.category} conflicts</button>}
  </section>)}{conflicts.map(site => <section key={site.hostname} className="mt-4 rounded-lg border border-[#FB8C00] p-4">
    <h3 className="text-sm font-medium"><span className="selectable">{site.hostname}</span> · {site.disposition === 'incompatible' ? 'Incompatible' : 'Review conflict'}</h3>
    <p className="mt-2 text-xs leading-5 text-[#606060]">{site.disposition === 'incompatible' ? 'This identity collides with protected or multiple Site definitions. Keep it or skip it.' : `Changed: ${site.differences?.join(', ')}. Replacement changes the Site definition and regenerated configuration. Files in document roots stay untouched.`}</p>
    <dl className="mt-3 grid gap-3 text-xs sm:grid-cols-2">{(['local', 'incoming'] as const).map(key => <div key={key}><dt className="font-medium">{key === 'local' ? 'Existing' : 'Backup'}</dt><dd className="mt-2 break-all">{site[key] ? ['name', 'hostname', 'aliases', 'documentRoot', 'https', 'rewriteEnabled', 'indexFiles'].map(field => <p key={field}>{field}: <span className="selectable">{JSON.stringify(site[key]![field])}</span></p>) : 'Multiple or protected identities'}</dd></div>)}</dl>
    <label className="mt-4 block text-sm">Action<select disabled={disabled || comparing} className="input mt-2" value={choices[site.hostname] ?? ''} onChange={event => onChange({ ...choices, [site.hostname]: event.target.value as BackupChoices[string] })}><option value="" disabled>Choose an action</option><option value="keep">Keep Existing</option>{site.disposition === 'conflict' && <option value="replace">Replace with Backup</option>}<option value="skip">Skip</option></select></label>
    {choices[site.hostname] && conflicts.filter(item => item.disposition === site.disposition && !choices[item.hostname]).length > 0 && <button disabled={disabled || comparing} className="mt-3 h-9 rounded-full border border-[#E5E5E5] px-4 text-sm font-medium" onClick={() => onChange({ ...Object.fromEntries(conflicts.filter(item => item.disposition === site.disposition && !choices[item.hostname]).map(item => [item.hostname, choices[site.hostname]])), ...choices })}>Apply choice to remaining Site conflicts</button>}
  </section>)}</>
}
export const unresolvedBackup = (backup: BackupPreview, choices: BackupChoices) => backup.sites.some(site => ['conflict', 'incompatible'].includes(site.disposition) && !choices[site.hostname]) || Boolean([...(backup.configurationItems ?? []), ...(backup.databaseItems ?? [])].some(item => ['conflict', 'incompatible'].includes(item.disposition) && !choices[item.key]))
