import { useState } from 'react'
import type { Site, VhostraState } from '../types/domain'
import type { VhostraDesktopApi } from '../types/desktop-api'
export function SiteDetails({ site, state, refresh, mappings: allMappings }: { site: Site; state: VhostraState; refresh: () => Promise<void>; mappings: Awaited<ReturnType<VhostraDesktopApi['hostsStatus']>> }) {
  const host = state.virtualHosts.find(host => host.id === site.vhostId)
  const [details, setDetails] = useState<Awaited<ReturnType<VhostraDesktopApi['siteDetails']>> | null>(null)
  const mappings = allMappings.filter(mapping => [host?.hostname, ...(host?.aliases ?? [])].includes(mapping.hostname))
  const [busy, setBusy] = useState(false); const [notice, setNotice] = useState<string | null>(null)
  const repair = async () => { setBusy(true); setNotice('Repairing configuration and local mappings; administrator approval may be required…'); try { const result = await window.vhostra!.repairSite(site.vhostId); setNotice(result.message); await refresh() } catch (reason) { setNotice(String(reason)) } finally { setBusy(false) } }
  const rewrite = async (enabled: boolean) => { setBusy(true); setNotice('Applying Site rewrite setting…'); try { await window.vhostra!.setVirtualHostRewrite(site.vhostId, enabled); await refresh(); setNotice('Site rewrite setting applied and validated.') } catch (reason) { setNotice(String(reason)); await refresh() } finally { setBusy(false) } }
  return <div className="mt-3 text-xs text-[#606060]"><p>Aliases: <span className="selectable">{host?.aliases.join(', ') || 'None'}</span> · PHP / LSPHP {state.settings.selectedPhpVersion} · {host?.https.enabled ? 'HTTPS requested · local certificate (trust separately)' : 'HTTP'}</p>{mappings.map(mapping => <p key={mapping.hostname} className="mt-1"><span className="selectable">{mapping.hostname}</span> — {mapping.state === 'required' ? mapping.issue ?? 'Missing mapping · permission required to repair' : mapping.state === 'conflict' ? `Conflict: ${mapping.address}` : 'Mapped'}</p>)}{host?.logs.paths && <dl className="mt-3 space-y-2"><div><dt className="font-medium">Access Log</dt><dd className="selectable break-all font-mono">{host.logs.paths.access}</dd></div><div><dt className="font-medium">Error Log</dt><dd className="selectable break-all font-mono">{host.logs.paths.error}</dd></div></dl>}<div className="mt-3 flex flex-wrap gap-3">{!site.builtIn && <button disabled={busy} onClick={() => void repair()} className="h-9 rounded-full border border-[#E5E5E5] px-4 font-medium disabled:opacity-50 text-sm">{busy ? 'Repairing…' : 'Repair Site'}</button>}<label className="flex items-center gap-2"><input type="checkbox" checked={host?.rewriteEnabled !== false} disabled={busy} onChange={event => void rewrite(event.target.checked)}/>Rewrite / permalinks</label></div>{<details className="mt-3" onToggle={event => { if (event.currentTarget.open) void window.vhostra!.siteDetails(site.id, true).then(setDetails).catch(reason => setNotice(String(reason))) }}><summary className="cursor-pointer font-medium">Configuration and import details</summary><p className="mt-3 font-medium">Current generated server configuration</p><p className="mt-2 break-all font-mono">{details?.nativePath ? <span className="selectable">{details.nativePath}</span> : 'Loading generated configuration…'}</p><pre className={`${details?.native ? 'selectable ' : ''}mt-2 max-h-64 overflow-auto whitespace-pre-wrap break-all rounded-lg bg-[#F2F2F2] p-3 font-mono`}>{details?.native ?? 'Loading…'}</pre>{details && <details className="mt-3"><summary className="cursor-pointer font-medium">Canonical server-neutral configuration</summary><pre className="selectable mt-2 max-h-64 overflow-auto whitespace-pre-wrap break-all font-mono">{JSON.stringify(details.host, null, 2)}</pre></details>}{host?.source && <p className="mt-3">Imported from {host.source.server}: <span className="selectable">{host.source.path}</span>. {host.source.warnings?.join(' ')}</p>}{host?.preservedDirectives?.length ? <pre className="selectable mt-2 max-h-48 overflow-auto whitespace-pre-wrap break-all font-mono">Inactive source directives: {host.preservedDirectives.join('\n')}</pre> : null}</details>}{notice && <p role="status" className="selectable mt-3">{notice}</p>}</div>
}
